swagger: "2.0"
info:
  title: Tlend
  version: "1.0"
  description: "project Tlend's server API"

host: http://
basePath:
schemes:
- http
- https
paths:
  # 주식상품 등록하기
  /stock:
    post:
      summary: 주식상품 등록하기 (개발완료)
      description: 주식상품 등록하기
      consumes:
      - form-data
      tags:
      - stock
      parameters:
      - in: body
        name: "body parameter"
        required: true
        schema:
          $ref: "#/definitions/insert_stock"
      responses:
        200:
          description: status code 200
          schema:
            type: object
            properties:
              message:
                type: string
                example: successfully insert stock item
                description: 성공 메시지
        403:
          description: status code 403
          schema:
            $ref: '#/definitions/403_error'

        500:
          description: status code 500
          schema:
            $ref: '#/definitions/500_error'



# response 공통 값
definitions:
  insert_stock:
    type: "object"
    required:
    - username
    properties:
      title:
        type: string
        description: 주식상품 제목
      goalMoney:
        type: integer
        description: 주식상품 설명
      price:
        type: integer
        description: 주당가격
      minPrice:
        type: integer
        description: 최소투자가능금액
      comValue:
        type: integer
        description: 현재기업가치
      schedule:
        type: string
        description: 발행예정 주식수
      repayDate:
        type: string
        description: 상환 청구기간
      startDate:
        type: string
        description: 펀딩 시작일
      enterDate:
        type: string
        description: 증권 입고일
      video:
        type: string
        description: 주식상품 동영상
      image:
        type: string
        description: 주식 상품 이미지
      categoryName:
        type: string
        description: 카테고리


  # Internal Server Error
  500_error:
    type: object
    properties:
      message:
        type: string
        example: Internal Server Error
  # Unauthorized
  401_error:
    type: object
    properties:
      message:
        type: string
        example: Unauthorized
  # Forbidden
  403_error:
    type: object
    properties:
      message:
        type: string
        example: Forbidden
  # Conflict Error
  409_error:
    type: object
    properties:
      message:
        type: string
        example: Conflict Error
  # Validation
  422_error:
    type: object
    properties:
      message:
        type: string
        example: Validation Error
